### ISSUE TITLE
BlahDNS filterlist is outdated and whitelist some domains 

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#133]
Hi,

I've seen your post about [filterlists](https://www.ookangzheng.com/filterlist/), and the blahdns's [blacklist](https://oooo.b-cdn.net/blahdns/adsblock.txt) {Please update this}. 

But what combination of blacklists is used in BlahDNS? You must have some sources, right?

**Comment by ookangzheng** [comment]
Sorry about that. Recently I'm still with my work.

**Comment by obeho** [comment]
👍  It'd be better to automate the list updation imo.

> what combination of blacklists is used in BlahDNS? 

You still haven't answered my question.

**Comment by ookangzheng** [comment]
Those links listed on my blog is used by on working + personal computer with uBlockOrigin + Adguard mac ios android (https://adguard.com/en/adguard-mac/overview.html)

**Comment by obeho** [comment]
> Those links listed on my blog is used by on working + personal computer with uBlockOrigin + Adguard mac ios android

👍  got it

> BlahDNS blacklist source: https://github.com/ookangzheng/blahdns/blob/master/hosts/source.txt

Thanks.

> It'd be better to automate the list updation imo.

I was referring to this [list](https://oooo.b-cdn.net/blahdns/adsblock.txt). Users should have real-time access to the current domain blocklist thats being used at the servers, which is not the case currently. `# Last updated:    May 25 00:33:10 UTC 2020`

Also, how often is the blocklist in use at the servers updated from these individual [sources](https://github.com/ookangzheng/blahdns/blob/master/hosts/source.txt)?

**Comment by ookangzheng** [comment]
The list for adblock_hosts or rpz has been update.
Usually, those lists will sync in between 24 ~ 48 hours. 

1. https://oooo.b-cdn.net/blahdns/adfilter_rpz.txt
2. https://oooo.b-cdn.net/blahdns/adfilter_hosts.txt

**Comment by obeho** [comment]
So, these lists are called every 24~48 hrs for any updates?

> https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/cert-pa.txt
https://raw.githubusercontent.com/scafroglia93/hosts-blocklists/master/yoroi.txt
https://raw.githubusercontent.com/nextdns/cname-cloaking-blocklist/master/domains
https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts
https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
http://theantisocialengineer.com/AntiSocial_Blacklist_Community_V1.txt
https://hblock.molinero.dev/hosts
https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt
https://hosts.nfz.moe/full/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt
https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
https://kriskintel.com/ktip_corona.txt
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt
https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt
https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker
https://280blocker.net/files/280blocker_domain.txt

**Comment by ookangzheng** [comment]
Yes, but still I will continue to tweak those blacklist.

**Comment by obeho** [comment]
👍 I saw you are adding and deleting lists.

Btw, this [list](https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt) you are maintaining by mirroring from the original dbl-oisd-nl, how often does it call the original list for updates?

**Comment by ookangzheng** [comment]
It depends on oisd.nl author. He will call my endpoint, and I will start to crawl the latest version.

**Comment by obeho** [comment]
Oh 😮 . Thats interesting. Why would he call your endpoint? Is there a dependency?

**Comment by ookangzheng** [comment]
Just a trigger. 
Cuz I don't know when he will update those lists. 
Therefore, he gonna trigger my endpoint (notice me). Then I will start to crawl all lists and upload them to Github / Gitlab.

**Comment by obeho** [comment]
Thats cool. I just wish all blocklists out there do the same. Thanks

**Comment by ookangzheng** [comment]
Nope, there are separate.

**Comment by obeho** [comment]
> Nope, there are separate.

Oh, so you automate it?

`perf.hsforms.com` domain is in the blocklist. Is this the reason why I was unable to open their [site](https://forms.hsforms.com/)? Due to CNAME?

**Comment by ookangzheng** [comment]
https://forms.hsforms.com/ is not in blahdns

**Comment by obeho** [comment]
Yes, this site `https://forms.hsforms.com/` isn't in blahdns's blocklist. Actually it redirects to `https://developers.hubspot.com/`.

When I open `https://developers.hubspot.com/` it works fine. But when I open `https://forms.hsforms.com/` its not getting redirected, both on my mobile and on my PC. See the below pic from DNS app on my mobile. I think `perf.hsforms.com` domain is critical for that redirect.

Due to this, domains like `https://share.hsforms.com/1N6aQgP9bQq2SmRziqOqMTw16gmf` aren't getting loaded. This site is just like google forms. And many other domain which contain `hsforms.com` in the name also aren't getting loaded.

![Screenshot_2020-10-24-00-00-54-34_c8cbde12d3521911922be4eee6a05664](https://user-images.githubusercontent.com/71698631/97041430-80c97d00-14fa-11eb-9782-192541372cea.jpg)

**Comment by ookangzheng** [comment]
Whitelisted `hsforms.com`

**Comment by obeho** [comment]
Thanks.

Google's CAPTCHA won't load if `www.recaptcha.net` is blocked. Please whitelist it.

**Comment by ookangzheng** [comment]
`www.recaptcha.net` fixed.

**Comment by obeho** [comment]
Thanks. Which list was it from? It doesn't deserve to be on BlahDNS's blocklist. Its as if blocking google.com.

**Comment by ookangzheng** [comment]
It does not block google.com though, maybe miss configure `www.recaptcha.net`
Found on this: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

**Comment by obeho** [comment]
But this Gooler's list isn't even used in BlahDNS, right?

**Comment by ookangzheng** [comment]
It used to be, but I removed a couple of hours ago.

**Comment by obeho** [comment]
Could you check Pull requests once?

**Comment by obeho** [comment]
Please whitelist `thenextweb.us1.list-manage.com` its a link from newsletter, but dont whitelist `list-manage.com`

**Comment by ookangzheng** [comment]
`thenextweb.us1.list-manage.com` fixed

**Comment by obeho** [comment]
Thanks, 

I had problems with `https://doh-fi.blahdns.com/dns-query` server 12.5hrs back, HTTP_ERROR displayed, both on my broadband connection, and mobile data. I checked with `https://stats.blahdns.com/`, it showed no downtime. Did you hear anything?

**Comment by ookangzheng** [comment]
is this still situation happen? 
cuz my server almost at bottle neck.

**Comment by obeho** [comment]
> I cant guarantee service at this `moment.

The bottleneck problem only at Finland server?

**Comment by obeho** [comment]
Are the Finland server queries forwarded to Germany? Coz I'm using `https://doh-fi.blahdns.com/dns-query` but dnsleak test shows

![Screenshot_2020-10-30 DNS leak test](https://user-images.githubusercontent.com/71698631/97658966-053b6480-1a01-11eb-9bcf-4d2314f24d38.png)

**Comment by ookangzheng** [comment]
when local DNS resolver is busy, it will forward to quad9 upstream. 
Quad9 route finland traffic to Germany pop.

Note, 
Don't have to worry abt DNS leak. 
DNS leak means test result same as your ISP default DNS.
Also upstream cant see your IP, All incoming IP has been replace as Finland server IP

**Comment by obeho** [comment]
Thanks @ookangzheng 

> Automate AdBlock sources update on server / CDN


Can you tell how this is done? Is it direct .txt file updating from the links like `https://raw.githubusercontent.com/........txt` ?

**Comment by ookangzheng** [comment]
> Thanks @ookangzheng
> 
> > Automate AdBlock sources update on server / CDN
> 
> Can you tell how this is done? Is it direct .txt file updating from the links like `https://raw.githubusercontent.com/........txt` ?

it upload to a file storage server, and CDN pop will fetch latest version to edge server around the world.

**Comment by obeho** [comment]
👍 

I observed that recently the response to domains in blacklist is changed from 0.0.0.0 to NXDOMAIN. Is there any specific reason? I'm asking because NXDOMAIN is considered an ambiguous choice for this, as it can be bad where clients try to resolve hostnames repeatedly as they don’t accept NXDOMAIN as reply, thereby polluting DNS queries.

**Comment by ookangzheng** [comment]
By using Knot-resolver blocking domain via RPZ, it can be config to return `NXDOMAIN` only.

**Comment by obeho** [comment]
0.0.0.0不是比NXDOMAIN更好吗？

**Comment by ookangzheng** [comment]
domain: `starsunfolded.com` whitelisted

**Comment by obeho** [comment]
`xnxx.com` whitelist please

**Comment by ookangzheng** [comment]
Fixed. 
xnxx.com found on

1. https://github.com/privacy-protection-tools/anti-AD
2. https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
3. https://github.com/neodevpro/neodevhost

**Comment by obeho** [comment]
`docs.google.com` whitelist please

**Comment by ookangzheng** [comment]
`docs.google.com` isn't in the blocklist though, try it again.

**Comment by obeho** [comment]
Now, its loading. My firewall showed it as blocked by the resolver. I even checked the blahdns txt file, the domain was in it. Now, it was removed by whichever list it came from.

**Comment by obeho** [comment]
`forum.xnxx.com` whitelist please

**Comment by obeho** [comment]
I think you should replace Stevenblack master hosts list with his {Unified hosts + fakenews + gambling + social} list `https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts`

Basically, whitelisting porn domains.

**Comment by ookangzheng** [comment]
![image](https://user-images.githubusercontent.com/6301735/98492772-d67c8400-2273-11eb-8251-db96731f675c.png)
still include `*.xnxx.com`

**Comment by obeho** [comment]
Yeah, but those domains aren't necessary to use the site properly.

Lite, keep using the master list but whitelist `xnxx.com` & `forum.xnxx.com` . If the master hosts list becomes aggressive in the future, we can change it to {Unified hosts + fakenews + gambling + social} list.

I still can't access `forum.xnxx.com`, did you whitelist it?

Also, whitelist `reddit.com` 🤦 

![pic (2)](https://user-images.githubusercontent.com/71698631/98503246-5ad4f580-21e7-11eb-9a7f-7d58836052a4.png)

**Comment by ookangzheng** [comment]
Already whitelist.

**Comment by obeho** [comment]
`sia.tech` whitelist please.

`https://rescure.fruxlabs.com/rescure_domain_blacklist.txt` blocklist is used at the blahdns servers, but the domain `rescure.fruxlabs.com` is blocked by another blocklist you use`https://kriskintel.com/feeds/ktip_covid_domains.txt` (this issue has been resolved because kriskintel removed froxlabs domain from their list), but still, how reliable is fruxlabs?

**Comment by ookangzheng** [comment]
Already removed krisintel.com source from blacklist.

**Comment by obeho** [comment]
`ouo.io` whitelist please

**Comment by obeho** [comment]
`cn.pool.ntp.org` from which list @ookangzheng ??

**Comment by ookangzheng** [comment]
`ouo.io` whitelisted.

`cn.pool.ntp.org` is under my custom blocklist on the server. 
I remember it used to be some attack (kinda), which slows down the entire server.

**Comment by obeho** [comment]
Yeah, thats because, each device android/windows/linux pings pool server every few minutes, so you will be looking at a lot of queries simultanoeusly. 😄

**Comment by obeho** [comment]
We blockling `www.google.com` now? @ookangzheng

**Comment by obeho** [comment]
didnt see #146 ✌️  . I'm curious, which blocklist it came from?

**Comment by ookangzheng** [comment]
No idea.
bcuz of blacklist continue update, when i notice this issue, it became impossible to track from which list.

**Comment by obeho** [comment]
please whitelist `trk.mail.ru`

**Comment by ookangzheng** [comment]
`trk.mail.ru`
fixed.

**Comment by obeho** [comment]
whitelist `ghostbin.co` please

**Comment by ookangzheng** [comment]
ghostbin.co not found🤔

**Comment by danyeet** [comment]
Could you please whitelist ```24chasa.bg``` ?

**Comment by ookangzheng** [comment]
`24chasa.bg` Done ~

**Comment by obeho** [comment]
please whitelist `softonic.com`

**Comment by ookangzheng** [comment]
Done ~ `softonic.com`

**Comment by obeho** [comment]
`www.godaddy.com` @ookangzheng why is this still blocked?

I thought it was whitelisted after our [discussion](https://github.com/ookangzheng/blahdns/issues/133#issuecomment-726943469).

**Comment by ookangzheng** [comment]
`www.godaddy.com` Found in https://github.com/notracking/hosts-blocklists
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt

**Comment by obeho** [comment]
whitelist `fc-resources.fastcompany.com` please. I think one of its CNAME is being blocked.

**Comment by obeho** [comment]
please whitelist `mailchimp.com` 🤦

**Comment by ookangzheng** [comment]
`mailchimp.com` fixed and found from source: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
`cname.tradepub.com` fixed.

**Comment by obeho** [comment]
@ookangzheng Do we want to include a blocklist that doesn't have a mechanism to take false positive reports? (Like the above mentioned quidsup/notrack-blocklists)

I think such blocklist should be removed.

**Comment by ookangzheng** [comment]
Indeed, will remove it.

**Comment by obeho** [comment]
whitelist `leechpremium.link` please

**Comment by ookangzheng** [comment]
Try again 

> Since recent blacklist update, pornhub.com player, menu and search stopped working

**Comment by obeho** [comment]
I just checked, I think he meant the .org, anyways the issue is still persisting. I think because of this domain `ss.phncdn.com`. I tried this domain in the 'Check domain status' in the website, but it seems no domain is working there. Each domain I checked just shows 'Timeout', there seems to be an issue.

**Comment by obeho** [comment]
Please whitelist `twilio.com`

**Comment by obeho** [comment]
Please add these domains to blacklist @ookangzheng 
`pepodownload.mediatek.com` `qepodownload.mediatek.com` `pgepodownload.mediatek.com` `qgepodownload.mediatek.com`

**Comment by obeho** [comment]
@ookangzheng ??

**Comment by ookangzheng** [comment]
I already add mediatek into block list though, qq, xiaomi, oppo, snapchat still takes time to observe, test and gather feedback

**Comment by obeho** [comment]
`firebaseinstallations.googleapis.com`  if you see no issue blocking this domain, please add it to the blacklist (apparently it creates a unique ID for anytime a Firebase enabled application is installed)

**Comment by ookangzheng** [comment]
👌  I will try to on Japan server first. 

> `firebaseinstallations.googleapis.com` if you see no issue blocking this domain, please add it to the blacklist (apparently it creates a unique ID for anytime a Firebase enabled application is installed)

**Comment by obeho** [comment]
Cool.

> qq, xiaomi, oppo, snapchat still takes time to observe, test and gather feedback

These are being tested on Japan server too?

**Comment by ookangzheng** [comment]
Usually Xiaomi, Snapchat and others already applies on both regions. But I will exclude few domains which may break the app or bring bad UX for users. 
For example
Xiaomi: `account.xiaomi.com`
Snapchat: `snap.com`
Chinese site: `qq.com` `360.com` `sina.cn` `baidu.com` `sogou.com` `m.baidu.com`
Huawei's cloud: `dbankcloud.com` `grs.dbankcloud.eu` `grs.dbankcloud.com`

**Comment by ookangzheng** [comment]
I prefer block subdomains instead entire root domain. 
If that site already compromised or got hacked, then will consider block the entire domain.

**Comment by obeho** [comment]
> both regions

what do you mean?

**Comment by ookangzheng** [comment]
> > both regions
> 
> what do you mean?
Japan, Singapore, Finland, Germany, Switzerland

**Comment by ookangzheng** [comment]
> 👌 I will try to on Japan server first.
> `firebaseinstallations.googleapis.com` will break some app which heavy rely on firebase config, permission, db, etc..
> 
> > `firebaseinstallations.googleapis.com` if you see no issue blocking this domain, please add it to the blacklist (apparently it creates a unique ID for anytime a Firebase enabled application is installed)

I tested out like mobile app OpenSignal (Speedtest app) wont work without allowing `firebaseinstallations.googleapis.com`

**Comment by eiden2233** [comment]
Please whitelist https://deezer.page.link/

**Comment by obeho** [comment]
Some explanation/reason would be nice.

**Comment by obeho** [comment]
@ookangzheng  `edthoutfre.fun` add to blacklist please. category : 'Adware'

**Comment by obeho** [comment]
Also, could you add this [list](https://dbl.oisd.nl/basic/) to the blacklists source list?

**Comment by ookangzheng** [comment]
`edthoutfre.fun` done and ABP oisd is the default block list in my server

**Comment by obeho** [comment]
I'm talking about BlahDNS servers.

**Comment by ookangzheng** [comment]
> I'm talking about BlahDNS servers. I couldn't find oisd list in [here](https://github.com/ookangzheng/blahdns/blob/master/hosts/source.txt).

I updated the source list

**Comment by obeho** [comment]
[GoodbyeAds](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt) hasn't been updated in 3 months. In blocklist world that is a long duration. Perhaps it should be removed? And once the update happens it can be added back.

**Comment by obeho** [comment]
`kdnuggets.com` whitelist please

**Comment by 0450** [comment]
Now pornhub.com is blocked. Whitelist please

**Comment by obeho** [comment]
> Now pornhub.com is blocked. Whitelist please

Now working. I think some list added and dropped one of the necessary domains.

@ookangzheng you added any new blocklists at the resolving server?

**Comment by 0450** [comment]
> Now working. I think some list added and dropped one of the necessary domains.

Sill not working for me'

**Comment by obeho** [comment]
`www.pornhub.com` or its CNAME `pornhub.com` is blocked. But these two domains are not necessary for normal usage of the website. I suggest you to visit `pornhub.org` which is still working fine with all videos being played. If you could elaborate `not working for me` that would be good.

**Comment by 0450** [comment]
Www.pornhub.com or pornhub.org shows "refused to connect". Error goes away on other dns resolvers.

**Comment by ookangzheng** [comment]
> Www.pornhub.com or pornhub.org shows "refused to connect". Error goes away on other dns resolvers. At least on the sg server

Is this issue still existed?

**Comment by 0450** [comment]
No its not anymore

**Comment by What-Zit-Tooya** [comment]
@ookangzheng some domains `content.garena.com` should not be blocked, because it breaks [garena app](https://play.google.com/store/apps/details?id=com.garena.gaslite) to work, full link is `content.garena.com/gas/game_info/XX.json` 
XX is location game, like TH for Thailand, ID for Indonesia.
but there is also ads link like this: `content.garena.com/gas/ad_banner/splash_banner_id.json`
Dunno how to blacklist & whitelist these case.

**Comment by ookangzheng** [comment]
> @ookangzheng some domains `content.garena.com` should not be blocked, because it breaks [garena app](https://play.google.com/store/apps/details?id=com.garena.gaslite) to work, full link is `content.garena.com/gas/game_info/XX.json`
> XX is location game, like TH for Thailand, ID for Indonesia.
> but there is also ads link like this: `content.garena.com/gas/ad_banner/splash_banner_id.json`
> Dunno how to blacklist & whitelist these case.
> 
> Probably this work:
> ||content.garena.com/gas/ad_banner/*
> @@||content.garena.com/gas/game_info/*

DNS based adblock either whitelist `content.garena.com` or blacklist. 

Solution that you proposed only valid at client side,
```||content.garena.com/gas/ad_banner/*
@@||content.garena.com/gas/game_info/*
```
such as web browser with uBlock, AdGuard, etc.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> > @ookangzheng some domains `content.garena.com` should not be blocked, because it breaks [garena app](https://play.google.com/store/apps/details?id=com.garena.gaslite) to work, full link is `content.garena.com/gas/game_info/XX.json`
> > XX is location game, like TH for Thailand, ID for Indonesia.
> > but there is also ads link like this: `content.garena.com/gas/ad_banner/splash_banner_id.json`
> > Dunno how to blacklist & whitelist these case.
> > Probably this work:
> > ||content.garena.com/gas/ad_banner/*
> > @@||content.garena.com/gas/game_info/*
> 
> DNS based adblock either whitelist `content.garena.com` or blacklist.
> 
> Solution that you proposed only valid at client side,
> 
> ```
> @@||content.garena.com/gas/game_info/*
> ```
> 
> such as web browser with uBlock, AdGuard, etc.

So, would you whitelist that?
For blacklist, we can use client side Adblock.

**Comment by ookangzheng** [comment]
Fixed

**Comment by What-Zit-Tooya** [comment]
@ookangzheng after testing your DNS, seems it promising and faster than cloudflare + also block ads. i also combined with adguard, perfect.
i see in your blacklist there is [shareit app](https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps), you also block it. but i still have ads.
maybe this filter will block it (personally use and it works):
- `receiver-metis.infeng.site`
- `adconf.rqmob.com`
- `tracker.hellay.net`
- `dt.beyla.site`
- `www.pullcm.com`
- `www.pullcf.com`
- `ascribe.rqmob.com`
- `cdn.shareitgames.com`
Fyi, shareit wont connect if we turn on VPN, so we can use Private DNS feature to block it ads.

**Comment by ookangzheng** [comment]
> @ookangzheng after testing your DNS, seems it promising and faster than cloudflare + also block ads. i also combined with adguard, perfect.
> i see in your blacklist there is [shareit app](https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps), you also block it. but i still have ads.
> maybe this filter will block it (personally use and it works):
> 
>     * `receiver-metis.infeng.site`
> 
>     * `adconf.rqmob.com`
> 
>     * `tracker.hellay.net`
> 
>     * `dt.beyla.site`
> 
>     * `www.pullcm.com`
> 
>     * `www.pullcf.com`
> 
>     * `ascribe.rqmob.com`
> 
>     * `cdn.shareitgames.com`
>       Fyi, shareit wont connect if we turn on VPN, so we can use Private DNS feature to block it ads.

Try again?

**Comment by What-Zit-Tooya** [comment]
> 
> 
> > @ookangzheng after testing your DNS, seems it promising and faster than cloudflare + also block ads. i also combined with adguard, perfect.
> > i see in your blacklist there is [shareit app](https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps), you also block it. but i still have ads.
> > maybe this filter will block it (personally use and it works):
> > ```
> > * `receiver-metis.infeng.site`
> > 
> > * `adconf.rqmob.com`
> > 
> > * `tracker.hellay.net`
> > 
> > * `dt.beyla.site`
> > 
> > * `www.pullcm.com`
> > 
> > * `www.pullcf.com`
> > 
> > * `ascribe.rqmob.com`
> > 
> > * `cdn.shareitgames.com`
> >   Fyi, shareit wont connect if we turn on VPN, so we can use Private DNS feature to block it ads.
> > ```
> 
> Try again?

Perfect. 
May be still there is ads & tracking server, im still investigating it. If its found, i'll report.

**Comment by LinuxPanda** [comment]
Request to whitelist the subdomains of netcore.co.in as its an email service and has nothing to do with spam. Thanks.

**Comment by ookangzheng** [comment]
> Request to whitelist the subdomains of netcore.co.in, example https://cloudmail17.netcore.co.in as its an email service and has nothing to do with spam. Thanks.

@LinuxPanda , Fixed

**Comment by obeho** [comment]
`itgiblean.com` domain is in [oisd](https://dbl.oisd.nl/basic) list (added on June 27 '21), and absent in either of your personal whitelists. Yet, it isn't being blocked. @ookangzheng  What went wrong here?

![sss](https://user-images.githubusercontent.com/71698631/125458100-22c04891-20b9-411e-9860-4e9eec4e6c36.png)
